# THIS FILE IS AUTOMATICALLY GENERATED
# Project: B:\UCU Second year\Term 1\POC\Cyberpong\CyberPong.cydsn\CyberPong.cyprj
# Date: Wed, 27 Dec 2023 18:29:39 GMT
#set_units -time ns
create_clock -name {Clock(FFB)} -period 104.16666666666666 -waveform {0 52.0833333333333} [list [get_pins {ClockBlock/ff_div_7}]]
create_clock -name {ADC_intClock(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {UART_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {Clock_1(FFB)} -period 104.16666666666666 -waveform {0 52.0833333333333} [list [get_pins {ClockBlock/ff_div_10}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 5 11} -nominal_period 104.16666666666666 [list]
create_generated_clock -name {ADC_intClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 31 61} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 5 11} -nominal_period 104.16666666666666 [list]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for B:\UCU Second year\Term 1\POC\Cyberpong\CyberPong.cydsn\TopDesign\TopDesign.cysch
# Project: B:\UCU Second year\Term 1\POC\Cyberpong\CyberPong.cydsn\CyberPong.cyprj
# Date: Wed, 27 Dec 2023 18:29:34 GMT
